# Generated by Django 3.2 on 2023-05-17 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20230510_1946'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-created',), 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
